"""Generates the RASOLV film voiceover with Kokoro (local open-weights TTS) and the word-timed captions.
Each line is synthesised separately and placed at START[i] on the timeline. Word timings are estimated
from the audio itself: the longest internal silences are matched to the punctuation breaks, then words
inside each phrase are spread by syllable weight.
Writes out/vo/NN.wav, out/vo/lines.json (for score.py), captions.js (for index.html), out/rasolv_film.srt.
Usage: python3 vo.py <kokoro-v1.0.onnx> <voices-v1.0.bin> [voice]"""
import sys, json, os, re
import numpy as np, soundfile as sf

# (start time on the timeline, caption text, spoken text)
LINES = [
    (0.55,  "Customer support is messy.", None),
    (3.15,  "Emails. Chats. Tickets.", None),
    (5.45,  "Scattered across ten different tools.", None),
    (8.35,  "RASOLV makes it all make sense.", "Rasolv makes it all make sense."),
    (11.0,  "Every conversation lands in one smart inbox. Triaged, prioritized, and routed to the right person, automatically.", None),
    (19.25, "From the first message, to full resolution.", None),
    (22.75, "Built-in AI drafts the reply, spots the pattern, and learns from every fix.", None),
    (28.3,  "Faster answers. Happier customers.", None),
    (32.55, "RASOLV. Vision that solves.", "Rasolv. Vision that solves."),
]
BRAND = "ɹɑːzˈɑːlv"   # "rah-ZOLV", rhymes with "resolve" — same phonemes as ../vo.py


def syllables(w):
    w = re.sub(r"[^a-z]", "", w.lower())
    n = len(re.findall(r"[aeiouy]+", w)) - (1 if w.endswith("e") and not w.endswith("le") else 0)
    return max(1, n)


def word_times(audio, sr, words):
    """Return [(start, end)] per word, seconds relative to the clip start."""
    hop = int(sr * 0.01)
    rms = np.array([np.sqrt(np.mean(audio[i:i + hop] ** 2)) for i in range(0, len(audio) - hop, hop)])
    quiet = rms < max(0.004, rms.max() * 0.04)
    gaps, i = [], 0
    while i < len(quiet):  # internal silent runs of >= 60 ms
        if quiet[i]:
            j = i
            while j < len(quiet) and quiet[j]: j += 1
            if i > 0 and j < len(quiet) and j - i >= 6: gaps.append((i * 0.01, j * 0.01))
            i = j
        else: i += 1
    breaks = [k for k, w in enumerate(words[:-1]) if re.search(r"[.,;:!?]$", w)]
    gaps = sorted(sorted(gaps, key=lambda g: g[0] - g[1])[:len(breaks)])
    if len(gaps) != len(breaks): breaks = breaks[:len(gaps)]
    total = len(audio) / sr
    bounds = [0.0] + [x for g in gaps for x in g] + [total]
    segs, s0 = [], 0
    for b in breaks + [len(words) - 1]:
        segs.append(list(range(s0, b + 1))); s0 = b + 1
    out = [None] * len(words)
    for si, idx in enumerate(segs):
        a, b = bounds[2 * si], bounds[2 * si + 1]
        wts = np.array([syllables(words[k]) + 0.6 for k in idx], float)
        edges = a + (b - a) * np.concatenate([[0], np.cumsum(wts) / wts.sum()])
        for n, k in enumerate(idx): out[k] = (float(edges[n]), float(edges[n + 1]))
    return out


def srt_ts(t):
    ms = int(round(t * 1000)); h, ms = divmod(ms, 3600000); m, ms = divmod(ms, 60000); s, ms = divmod(ms, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def main():
    from kokoro_onnx import Kokoro
    from kokoro_onnx.tokenizer import Tokenizer
    model, voices = sys.argv[1], sys.argv[2]
    voice = sys.argv[3] if len(sys.argv) > 3 else "af_heart"
    k, tok = Kokoro(model, voices), Tokenizer()
    os.makedirs("out/vo", exist_ok=True)
    meta, caps, srt = [], [], []
    for i, (start, text, spoken) in enumerate(LINES):
        ph = tok.phonemize(spoken or text, "en-us").replace("ɹˈæsɑːlv", BRAND)
        audio, sr = k.create(ph, voice=voice, speed=1.0, is_phonemes=True)
        a = np.asarray(audio, dtype=np.float32)
        env = np.abs(a) > 0.01
        s = int(np.argmax(env)); e = len(a) - int(np.argmax(env[::-1]))
        a = a[max(0, s - int(0.02 * sr)): min(len(a), e + int(0.06 * sr))]
        sf.write(f"out/vo/{i:02d}.wav", a, sr)
        words = text.split()
        wt = word_times(a, sr, words)
        dur = len(a) / sr
        end = LINES[i + 1][0] if i + 1 < len(LINES) else start + dur + 1
        assert start + dur < end - 0.15, f"line {i} ({dur:.2f}s) overruns the next line"
        meta.append({"i": i, "start": start, "dur": round(dur, 3), "sr": sr, "text": text})
        caps.append({"start": start, "end": round(start + dur + 0.35, 3),
                     "words": [[w, round(start + a0, 3), round(start + a1, 3)] for w, (a0, a1) in zip(words, wt)]})
        srt.append(f"{i + 1}\n{srt_ts(start)} --> {srt_ts(start + dur + 0.2)}\n{text}\n")
        print(f"{i} {start:6.2f}+{dur:4.2f}  {text}  /{ph}/")
    json.dump({"voice": voice, "lines": meta}, open("out/vo/lines.json", "w"), indent=1)
    open("captions.js", "w").write("// generated by vo.py — word-timed captions\nwindow.CAPTIONS = " + json.dumps(caps) + ";\n")
    open("out/rasolv_film.srt", "w").write("\n".join(srt))

main()
